### PR TITLE
Fix for MD generation

### PR DESCRIPTION
**Pull request by Bourne-ID**
Change the JSON output to be an array of elements. 
Change the CSV parser to read each entity in turn, pipe to find the elements and output to CSV
Removed jq from MD generation - the NPM package will parse the json array

### CODE REVIEW

**Comment by dgibbs64** [comment]
Nice!!!

**Comment by dgibbs64** [comment]
Just ran a build seems to of broken the generation of the json file. You can see teh output on Travis.

**Comment by Bourne-ID** [comment]
That's unexpected... having a look now.

**Comment by Bourne-ID** [comment]
Looks like a steam server issue - the file size downloaded was 390 bytes, this should be in the MB. Can you re-run the build?

**Comment by dgibbs64** [comment]
Will do asap

**Comment by dgibbs64** [comment]
Done a new build worked fine. So further things to consider is some sort of error check should the URL not work correctly. Preventing creating empty files.

The JSON file is now all on one line.

A false positive file that removes appids that are not servers but contain the word 'server'.

I think if we get them 3 then that would be great. Then can look at adding further data like sizes, other useful info and maybe steamdb links.

Thanks for the fix

**Pull request merged**
